
-- size of our actual window
WINDOW_WIDTH = 1080
WINDOW_HEIGHT = 640

max_FPS = 60

PADDLE_SPEED = WINDOW_WIDTH
PADDLE_STARTX = WINDOW_WIDTH/2 - 32
PADDLE_STARTY = WINDOW_HEIGHT*0.9
PADDLE_STARTW = 64
PADDLE_STARTXH = 16

BALL_Y_SPEED = WINDOW_HEIGHT/3
BALL_X_SPEED = WINDOW_WIDTH/5
-- BALL_X_SPEED = 0